<a href="https://colab.research.google.com/github/shamsulalam1114/Linear_Regression/blob/main/Car.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
from sklearn import linear_model

In [5]:
from google.colab import files
uploaded = files.upload()

Saving car data.csv to car data.csv

In [9]:
df= pd.read_csv('car data.csv')

In [10]:
df

     speed  car_age  experience  risk
0      172       22    8.104042    42
1       94       17   11.429461    36
2      186       20   14.819477    45
3      151       10   15.343897    38
4      100        6   16.455807    47
..     ...      ...         ...   ...
275    165       10    8.630563    20
276    130       26    6.656316    49
277    142       19   14.610983    20
278    204        7   13.874352    45
279    137        3    3.334615    68

[280 rows x 4 columns]

In [11]:
df.experience

0       8.104042
1      11.429461
2      14.819477
3      15.343897
4      16.455807
         ...
275     8.630563
276     6.656316
277    14.610983
278    13.874352
279     3.334615
Name: experience, Length: 280, dtype: float64

In [16]:
exm_fit = df.experience.median()

In [17]:
exm_fit

10.582101444783259

In [19]:
df.experience= df.experience.fillna(exm_fit)

In [20]:
df.experience

0      <bound method NDFrame.fillna of 0       8.1040...
1      <bound method NDFrame.fillna of 0       8.1040...
2      <bound method NDFrame.fillna of 0       8.1040...
3      <bound method NDFrame.fillna of 0       8.1040...
4      <bound method NDFrame.fillna of 0       8.1040...
                             ...
275    <bound method NDFrame.fillna of 0       8.1040...
276    <bound method NDFrame.fillna of 0       8.1040...
277    <bound method NDFrame.fillna of 0       8.1040...
278    <bound method NDFrame.fillna of 0       8.1040...
279    <bound method NDFrame.fillna of 0       8.1040...
Name: experience, Length: 280, dtype: object

In [21]:
df

     speed  car_age                                         experience  risk
0      172       22  <bound method NDFrame.fillna of 0       8.1040...    42
1       94       17  <bound method NDFrame.fillna of 0       8.1040...    36
2      186       20  <bound method NDFrame.fillna of 0       8.1040...    45
3      151       10  <bound method NDFrame.fillna of 0       8.1040...    38
4      100        6  <bound method NDFrame.fillna of 0       8.1040...    47
..     ...      ...                                                ...   ...
275    165       10  <bound method NDFrame.fillna of 0       8.1040...    20
276    130       26  <bound method NDFrame.fillna of 0       8.1040...    49
277    142       19  <bound method NDFrame.fillna of 0       8.1040...    20
278    204        7  <bound method NDFrame.fillna of 0       8.1040...    45
279    137        3  <bound method NDFrame.fillna of 0       8.1040...    68

[280 rows x 4 columns]

In [22]:
reg= linear_model.LinearRegression()

In [24]:
print(df[['speed','car_age','experience']].dtypes)
print(df[['speed','car_age','experience']].head())
print(df['risk'].dtype, df['risk'].head())

speed          int64
car_age        int64
experience    object
dtype: object
   speed  car_age                                         experience
0    172       22  <bound method NDFrame.fillna of 0       8.1040...
1     94       17  <bound method NDFrame.fillna of 0       8.1040...
2    186       20  <bound method NDFrame.fillna of 0       8.1040...
3    151       10  <bound method NDFrame.fillna of 0       8.1040...
4    100        6  <bound method NDFrame.fillna of 0       8.1040...
int64 0    42
1    36
2    45
3    38
4    47
Name: risk, dtype: int64

In [25]:
for col in ['speed','car_age','experience','risk']:
    df[col] = pd.to_numeric(df[col], errors='coerce')

In [27]:
print(df.isna().sum())

speed           0
car_age         0
experience    280
risk            0
dtype: int64

In [28]:
df = df.dropna(subset=['speed','car_age','experience','risk'])

In [30]:
print(df.isna().sum())

speed         0
car_age       0
experience    0
risk          0
dtype: int64